import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { db } from '../utils/firebase'
import { onValue, ref } from 'firebase/database'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [waterDist, setWaterDist] = useState(0)
  useEffect(() => {
    console.log(process.env.NEXT_PUBLIC_API_KEY)
    const query = ref(db, "board1/inputs/WaterDist");
    return onValue(query, (snapshot) => {
      const data = snapshot.val();
      if (snapshot.exists()) {
        console.log(data);
        setWaterDist(data)
        // Object.values(data).map((project) => {
        //   setProjects((projects) => [...projects, project]);
        // });
      }
    });
  }, []);
  return (
    <>
      <Head>
        <title>Water Level Detection</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>
        Realtime Water Level Monitoring
      </p>
      <div class="container">
        <div class="barcontainer">
          <div class="bar" style={{height: `${(waterDist * 10)}%`}}>
          </div>
        </div>
      </div>
    </>
  )
}
