import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { db } from '../utils/firebase'
import { onValue, ref, set } from 'firebase/database'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [waterDist, setWaterDist] = useState(0)
  const [motorStatus, setMotorStatus] = useState(0)
  useEffect(() => {
    // waterLevel
    const query = ref(db, "board1/inputs/WaterDist");
    console.log("distTest",query)
    return onValue(query, (snapshot) => {
      const data = snapshot.val();
      if (snapshot.exists()) {
        console.log(data);
        setWaterDist(data)
        // Object.values(data).map((project) => {
        //   setProjects((projects) => [...projects, project]);
        // });
      }
    });
  }, []);

  useEffect(() => {
    // motorStatus
    const query = ref(db, "board2/motor/status");
    console.log("motortest",query)
    return onValue(query, (snapshot) => {
      const data = snapshot.val();
      console.log(data)
      if (snapshot.exists()) {
        console.log(data);
        setMotorStatus(data)
      }
    });
    
  }, []);

  const onButtonTrigger = () => {
    set(ref(db, 'board2/motor/onSwitch'), 1)
    .then(() => {
      console.log("on button Pressed")
    })
    .catch((error) => {
      // The write failed...
    });
  }

  const offButtonTrigger = () => {
    set(ref(db, 'board2/motor/offSwitch'), 1)
    .then(() => {
      console.log("off button Pressed")
    })
    .catch((error) => {
      // The write failed...
    });
  }

  return (
    <>
      <Head>
        <title>Water Level Detection</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>
        Realtime Water Level Monitoring
      </p>
      <div className='buttonGroup'>
        <button className='button onButton' onClick={onButtonTrigger}>
          On
        </button>
        <button className='button offButton' onClick={offButtonTrigger}>
          Off
        </button>
      </div>
      <div className='statusContainer'>
        {
          motorStatus === 0 ? 
          <p className='offStatus' >Motor Off</p>
          :
          <p className='onStatus'>motor On</p>
        }
      </div>
      <div className="container">
        <div className="barcontainer">
          <div className="bar" style={{height: `${((10-waterDist) * 10)}%`}}>
          </div>
        </div>
      </div>
    </>
  )
}
